### PR TITLE
Use CodeCov instead of Scrutinizer

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
@jwage @SenseException for some reason I don't have access to the settings for this repository, can you please remove the Scrutinizer webhook?

**Comment by greg0ire** [comment]
Also, it looks like the build is broken ATM?

```
PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "cd /home/travis/build/doctrine/doctrine-website/projects/mongodb-odm && git clean -xdf && git checkout origin/2.1.x" failed.

Exit Code: 1(General error)

Working directory: /home/travis/build/doctrine/doctrine-website

Output:

================

Error Output:

================

error: pathspec 'origin/2.1.x' did not match any file(s) known to git
```

**Comment by greg0ire** [comment]
@malarzm do you maybe know what happened to branch 2.1.x of the ODM?

**Comment by SenseException** [comment]
Branch issues are the most common one for the website build. I'm thinking about having a regular planned build just to check for these until a solution for this is provided.

The link on the readme page runs into a 404, which wasn't the case on your other CodeCov PRs. Is this currently expected?

**Comment by greg0ire** [comment]
> Is this currently expected?

Yes, since coverage reports are uploaded `after_success`, and the build failed.

**Comment by greg0ire** [comment]
I retriggered a build because of https://github.com/doctrine/mongodb-odm/pull/2201#issuecomment-647619008 :) Github's UI makes it dangerously easy to remove a branch…

**Comment by greg0ire** [comment]
Ok so now it's inflector's turn… 2.0.x no longer seems to exist :skull:

**Comment by greg0ire** [comment]
Green! @jwage @SenseException please address https://github.com/doctrine/doctrine-website/pull/348#issuecomment-646971812 and merge

**Comment by greg0ire** [comment]
Great! Please merge, I don't have the permission to do so apparently.

**Comment by SenseException** [comment]
Done. Thank you for introducing CodeCov.

**Pull request merged**
