### PR TITLE
show phpcr-bundle documentation

### PR DESCRIPTION
**Pull request by dbu**
i am adding the documentation in https://github.com/doctrine/DoctrinePHPCRBundle/pull/399 - does that look correct?

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Comment by derrabus** [comment]
Let's find out. 🙂

**Comment by dbu** [comment]
hm, deploying fails https://github.com/doctrine/doctrine-website/actions/runs/8537711875/job/23388867200

what makes the process think there is a  branch called `master`? i don't see a config for the default branch for e.g. DoctrineMigrationsBundle which also has no master branch.

**Comment by stof** [comment]
This run was before the merge of https://github.com/doctrine/DoctrinePHPCRBundle/commit/d3d19b641b3bf167a25687d918413ada27d6b32c adding the config file in the bundle.
Without a config file specifying versions, the website defaults to building a single version for the `master` branch

**Comment by dbu** [comment]
ah, thats why.

should we trigger a rerun? how frequently is the website rebuilt?

**Comment by stof** [comment]
Once a day by a cron + on every push to the master branch of this repo: https://github.com/doctrine/doctrine-website/blob/master/.github/workflows/deployment-prod.yml

**Comment by dbu** [comment]
seems to have worked, the bundle documentation is now online

**Pull request merged**
