### PR TITLE
Add flag to mark versions as in development

### PR DESCRIPTION
**Pull request by Majkl578**
Primarily for ORM 3.0, DBAL 3.0 and ODM 2.0.
(I'll rename _"master"_ to their respective versions once this is in + add DBAL develop.)

preview

### CODE REVIEW

**Comment by Majkl578** [comment]
Maybe _"upcoming"_ would be better? Not sure...

**Comment by carusogabriel** [comment]
Shouldn't we add https://github.com/doctrine/coding-standard

**Comment by jwage** [comment]
@Majkl578 do you mind if I take this idea and change it a little bit? I had some previous thoughts here.

**Comment by Majkl578** [comment]
Sure, feel free to expand it. :+1:

**Comment by jwage** [comment]
Continuing this work in #138

**Pull request closed without merging**
