### PR TITLE
Use final and readonly where possible

### PR DESCRIPTION
**Pull request by derrabus**
Finalizing classes/methods or flagging properties as readonly helps a reader understand how a class is used and what impact a code change may have. I propose to make `final` and `readonly` the default in this codebase.

### CODE REVIEW

**Comment by SenseException** [comment]
Why are some classes "just" `/** @final */`?

**Comment by derrabus** [comment]
Because we create mocks for those classes. 😢

**Review by SenseException — APPROVED** [review]
I'm currently working on increasing the test coverage. I'll come back to the final-annotation in case a mock is serviceable. I don't want to use `nunomaduro/mock-final-classes` on new tests.

**Comment by derrabus** [comment]
Sure, whenever you need to create a mock, feel free to un-finalize classes.

**Pull request merged**
