### PR TITLE
Doctrine DBAL 3.4.0 blog post

### PR DESCRIPTION
**Pull request by morozov**

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by morozov** [comment]
@SenseException I’ve just tagged the release. Could you merge and deploy thy, please?

**Comment by greg0ire** [comment]
@morozov do you have the necessary permissions to click that button, or do you want us to do that now. I'm AFK for a week and won't log in to Slack within that time.

**Comment by morozov** [comment]
No, I don’t have the merge permissions here.

**Comment by morozov** [comment]
Enjoy your time AFK, @greg0ire!

**Comment by SenseException** [comment]
Done.

**Pull request merged**
