### PR TITLE
Fixed white gap on right side of page

### PR DESCRIPTION
**Pull request by pushpak1300**
https://github.com/doctrine/doctrine-website/issues/341

### CODE REVIEW

**Comment by pushpak1300** [comment]
Can anyone review this pull request?

**Comment by SenseException** [comment]
I'll see if I can build the website and test the changes during this week. Please squash your commits in the meantime.

Please use `rebase` instead of `merge` when you update your branch with the latest changes of master in the future.

**Comment by pushpak1300** [comment]
I am not sure how to squash commit?
can you please provide any resource?

**Comment by SenseException** [comment]
Grégoire made in another PR a short howto. Maybe it might help you too: https://github.com/doctrine/orm/pull/8035#issuecomment-601830356

**Pull request closed without merging**
